name: Publish Shared library to NuGet
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/TTools.Configuration.KeyedOptions/**
jobs:
  publish_net6:
    name: Publish .NET Standard Library to NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dotNET
        id: install_dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - name: Publish NuGet Package
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: src/TTools.Configuration.KeyedOptions.Shared/TTools.Configuration.KeyedOptions.Shared.csproj
          PACKAGE_NAME: TTools.Configuration.KeyedOptions.Shared
          TAG_COMMIT: true
          TAG_FORMAT: v*-shared
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
